<?php

namespace Tests\Unit;

use App\Order;
use App\Product;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class OrderTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function an_order_consists_products()
    {
        $order = new Order();
        $product = new Product('iWatch', 3000);
        $productTwo = new Product('NDR-1000X', 2000);
        $order->add($product);
        $order->add($productTwo);

        $this->assertEquals(2,count($order->products()));
    }

    /** @test */
    public function we_can_get_total_cost_from_all_products_of_an_order()
    {
        $order = new Order();
        $product = new Product('iWatch', 3000);
        $productTwo = new Product('NDR-1000X', 2000);
        $order->add($product);
        $order->add($productTwo);

        $this->assertEquals(5000,$order->total());
    }
}
