<?php

namespace Tests\Unit;

use App\Order;
use App\Product;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class OrderTest extends TestCase
{
    protected $order;
    protected $product;
    protected $productTwo;

    /**
     * 前置钩子方法
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->order = new Order();
        $this->product = new Product('iWatch', 3000);
        $this->productTwo = new Product('NDR-1000X', 2000);
    }

    /** @test */
    public function an_order_consists_products()
    {
        $this->order->add($this->product);
        $this->order->add($this->productTwo);
        $this->assertEquals(2, count($this->order->products()));
    }

    /** @test */
    public function we_can_get_total_cost_from_all_products_of_an_order()
    {
        $this->order->add($this->product);
        $this->order->add($this->productTwo);
        $this->assertEquals(5000, $this->order->total());
    }
}
